// // criando uma função

//  function minhaFuncao() {
//     console.log("testando")
//  }

//  minhaFuncao();
// //   minhaFuncao();   aqui estou invocando a minha funcao, se tivesse algo nos parenteses eu coloca se n ok, ai assim aparece a mensagem no console


//  const minhaFuncaoEmVariavel = function () {
//     console.log("função em variavel") 

// }

// minhaFuncaoEmVariavel(); 
// // minhaFuncaoEmVariavel();  nessa situação aqui tambem esta invocando a função

// function funcaoComParametro(txt) {
//     console.log(`imprimindo: ${txt}`)
// }

//  funcaoComParametro("imprimindo alguma coisa")

// funcaoComParametro("outra função")
// funcaoComParametro("outra função otavio")


// return 

